- hosts: all
  user: vagrant
  become: yes
  vars:
    config_path: '/vagrant'
    home_path: '/home/vagrant'
    func_path: '/vagrant/source/func'
  roles:
    - php72
    - composer
    - zip&unzip
    - httpd
    - git
    - mongodb
    - php-twitter-git-config
    - python36&pip
    - mount
    - alias
    - fishykink
    - elasticsearch


    
